name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like
      description: Describe the feature and why it helps
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Extra details or examples
